require 'active_support/core_ext/object/inclusion'

load 'tasks/seed_fu.rake'

task :environment do
  require 'economatic_core'
end

namespace :db do
  namespace :schema do
    task :load => :environment do
      load File.join(Economatic::ROOT_PATH, 'db/schema.rb')
    end
  end
  task :drop => :environment do
    FileUtils.rm_f(File.join(Economatic::ROOT_PATH, 'db/test.sqlite'))
  end

  desc "rebuild the database from schema.rb"
  task :reset => :environment do
    task('db:drop').invoke
    task('db:schema:load').invoke
  end
end

require 'rspec/core/rake_task'

desc "Run specs"
RSpec::Core::RakeTask.new do |t|
end

require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = "features --format pretty -t ~@wip"
end

require 'coveralls/rake/task'
Coveralls::RakeTask.new

desc "Run cukes and specs"
task :ci => [:spec, :features] do
end

desc "Setup this app"
task :setup_ci do
  task('db:reset').invoke
end
