require 'active_support/core_ext/object/inclusion'

load 'tasks/seed_fu.rake'

@root_dir =  File.join(File.dirname(__FILE__))
require 'economatic_rake'
require 'rspec/core/rake_task'

desc "Run specs"
RSpec::Core::RakeTask.new do |t|
end

require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = "features --format pretty -t ~@wip"
end

require 'coveralls/rake/task'
Coveralls::RakeTask.new

desc "Run cukes and specs"
task :ci => [:spec, :features] do
end

desc "Setup this app"
task :setup_ci do
  task('db:reset').invoke
end
