source "http://rubygems.org"

gem 'rake'
gem 'playhouse', git: 'git://github.com/enspiral/playhouse.git'
gem 'playhouse-sinatra', path: '../playhouse-sinatra'
gem 'economatic', path: '../economatic'
gem 'economatic-sinatra', path: '.'

gem 'capybara'
gem 'cucumber'
