@root_dir =  File.join(File.dirname(__FILE__))
require 'economatic_rake'

desc "Setup this app"
task :setup_ci do
  task('db:reset').invoke
end

require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = "features --format pretty -t ~@wip"
end

desc "Run cukes"
task :ci => [:features] do
end

task default: :ci

