require 'rspec/core/rake_task'

desc "Run specs"
RSpec::Core::RakeTask.new do |t|
end

desc "Setup this console interface for CI"
task :setup_ci do
  puts "nothing to setup"
end

desc "Test this console interface"
task :ci => [:spec] do
end
